//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retrosheet_Persist
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Data
    {
        public System.Guid record_id { get; set; }
        public string game_id { get; set; }
        public string data_type { get; set; }
        public string player_id { get; set; }
        public string data_value { get; set; }
    }
}
