//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retrosheet_Persist
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public System.Guid record_id { get; set; }
        public string team_id { get; set; }
        public string league { get; set; }
        public string city { get; set; }
        public string name { get; set; }
        public string season_game_type { get; set; }
        public string season_year { get; set; }
    }
}
