//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retrosheet_RetrieveData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batter_Adjustment
    {
        public System.Guid record_id { get; set; }
        public string game_id { get; set; }
        public int inning { get; set; }
        public int game_team_code { get; set; }
        public int sequence { get; set; }
        public string player_id { get; set; }
        public string bats { get; set; }
        public string team_id { get; set; }
    }
}
