//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retrosheet_RetrieveData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel
    {
        public System.Guid record_id { get; set; }
        public string person_id { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public System.DateTime career_date { get; set; }
        public string role { get; set; }
    }
}
