//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retrosheet_RetrieveData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Play
    {
        public System.Guid record_id { get; set; }
        public string game_id { get; set; }
        public int inning { get; set; }
        public int game_team_code { get; set; }
        public int sequence { get; set; }
        public string player_id { get; set; }
        public Nullable<int> count_balls { get; set; }
        public Nullable<int> count_strikes { get; set; }
        public string pitches { get; set; }
        public string event_sequence { get; set; }
        public string event_modifier { get; set; }
        public string event_runner_advance { get; set; }
        public string event_columnSix { get; set; }
        public string event_fielded_by { get; set; }
        public string event_hit_location { get; set; }
        public Nullable<int> event_num { get; set; }
        public string event_play_on_runner { get; set; }
        public string event_type { get; set; }
        public string season_game_type { get; set; }
        public string season_year { get; set; }
    }
}
