//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retrosheet_RetrieveData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public System.Guid record_id { get; set; }
        public string player_id { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string throws { get; set; }
        public string bats { get; set; }
        public string team_id { get; set; }
        public string field_position { get; set; }
        public string season_game_type { get; set; }
        public string season_year { get; set; }
    }
}
