//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retrosheet_RetrieveData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Substitute_Umpire
    {
        public System.Guid record_id { get; set; }
        public string game_id { get; set; }
        public int inning { get; set; }
        public int sequence { get; set; }
        public Nullable<int> comment_sequence { get; set; }
        public string field_position { get; set; }
        public string umpire_id { get; set; }
    }
}
